import type { Metadata } from "next";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
      {/* Sidebar fixo */}
      <aside className="hidden md:block border-r bg-muted/40 h-screen sticky top-0">
        <Sidebar />
      </aside>

      {/* Conteúdo com rolagem */}
      <div className="flex flex-col w-full h-screen overflow-hidden">
        <Header />
        <main className="flex-1 overflow-auto p-4">{children}</main>
      </div>
    </div>
  );
}
